application: connexus-fall15
version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css
- url: /assets
  static_dir: assets

- url: /.*
  script: connexus.app

- url: /.*
  script: trending.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
